### Crear unidad
POST http://localhost:8080/api/unit
Content-Type: application/json

{
  "name": "Kilogramo",
  "abbreviation": "kg",
  "active": true
}

###

### Obtener todas
GET http://localhost:8080/api/unit

###

### Obtener por id
GET http://localhost:8080/api/unit/1

###

### Actualizar
PUT http://localhost:8080/api/unit/1
Content-Type: application/json

{
  "name": "Kilogramo",
  "abbreviation": "KG",
  "active": true
}

###

### Eliminar
DELETE http://localhost:8080/api/unit/1