POST http://localhost:8080/api/inventory-movements
Content-Type: application/json

{
  "productId": "4f3b7b68-1d69-4df4-b8fd-0e5c31fcd2d1",
  "movementTypeId": 1,
  "sourceTypeId": 1,
  "sourceId": null,
  "quantity": 10,
  "observations": "Entrada inicial"
}

###
GET http://localhost:8080/api/inventory-movements
###
GET http://localhost:8080/api/inventory-movements/4f3b7b68-1d69-4df4-b8fd-0e5c31fcd2d1
###
PUT http://localhost:8080/api/inventory-movements/4f3b7b68-1d69-4df4-b8fd-0e5c31fcd2d1
Content-Type: application/json

{
  "productId": "4f3b7b68-1d69-4df4-b8fd-0e5c31fcd2d1",
  "movementTypeId": 1,
  "sourceTypeId": 1,
  "sourceId": null,
  "quantity": 25,
  "observations": "Actualización"
}
###
DELETE http://localhost:8080/api/inventory-movements/4f3b7b68-1d69-4df4-b8fd-0e5c31fcd2d1