-- PRODUCT CATEGORY
ALTER TABLE product_category
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE product_category
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();


-- UNIT
ALTER TABLE unit
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE unit
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();


-- ROLE
ALTER TABLE role
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE role
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();


-- MOVEMENT TYPE
ALTER TABLE movement_type
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE movement_type
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();


-- SOURCE TYPE
ALTER TABLE source_type
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE source_type
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();


-- ORDER STATUS
ALTER TABLE order_status
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE order_status
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();


-- PRODUCTION OPERATION
ALTER TABLE production_operation
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE production_operation
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();