spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/mantas_guajiras_db
    username: postgres
    password: TU_CONTRASEÑA
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO